### ISSUE TITLE
Adding Keyboard Shortcut-Keys CheatSheet

### ISSUE THREAD

**Issue by Aman-Singh-Kushwaha** [codemistic/Non-Code#14]
One cannot **Learn ** all shortcut keys, So
I can add all keyboard shortcut keys in the cheatsheet section

This may help to get work easier and save lots of time and efforts

**Comment by TKirtan** [comment]
> One cannot **Learn ** all shortcut keys, So
> I can add all keyboard shortcut keys in the cheatsheet section
> 
> This may help to get work easier and save lots of time and efforts

Great, You can create a file for that and send a pull request.

**Comment by Aman-Singh-Kushwaha** [comment]
@gantavyamalviya should i commit in .txt file or .md file

Also do assign it to me with hacktoberfest label

**Comment by TKirtan** [comment]
I think .md file would be great, as it is rendered well in GitHub as well as other platforms.

**Comment by Ayushbajpai19** [comment]
I would like to contribute in this repo for hacktoberfest.

**Comment by Aman-Singh-Kushwaha** [comment]
@Ayushbajpai19  j am working on it about to complete

**Comment by Abhash-Chakraborty** [comment]
Can you assign me

**Comment by Aman-Singh-Kushwaha** [comment]
Since Final PR #107 has been merged , I am closing this issue.
