### ISSUE TITLE
⭐ Ubuntu-22.04 cheat Sheet added 

### ISSUE THREAD

**Issue by Suryansh1720001** [codemistic/Non-Code#163]
Hi @codemistic ,
This Cheat sheet is related to a linux operating system which is Ubuntu-22.04. I want to do work in this subject.
I'd like to contribute to this issue with this New topic.
Thank you

**Comment by astitva0011** [comment]
hello, i would like to work on this issue. 
could you assign this issue to me?

**Comment by TKirtan** [comment]
Linux cheatsheet is already present in the repo. Please find another issue to work on.
