### ISSUE TITLE
Add communication skills roadmap

### ISSUE THREAD

**Issue by ADITIBAGADDEO22** [codemistic/Non-Code#208]

**Comment by ADITIBAGADDEO22** [comment]
I think communication skills are very necessary so,  I want to create a folder and add a file which will describe communication skills. 
please assign this task to me.

**Comment by ADITIBAGADDEO22** [comment]
@TKirtan please add hacktoberfest-accepted label to it

**Comment by TKirtan** [comment]
Good, Keep in mind don't send pull request with any kind of copywrited content. Read CodeofConduct.

**Comment by manasbhandari** [comment]
heyy @TKirtan
i think i can do this in a very better way. please assign this task to me so that i can work on it .

**Comment by ADITIBAGADDEO22** [comment]
@TKirtan I completed my task please merge it.

**Comment by TKirtan** [comment]
> heyy @TKirtan i think i can do this in a very better way. please assign this task to me so that i can work on it .

It's already assigned to someone, please find another issue to work on.

**Comment by TKirtan** [comment]
> @TKirtan I completed my task please merge it.

Okay, you can close the issue.
