### ISSUE TITLE
Add web development cheatsheets

### ISSUE THREAD

**Issue by ShrutiMishra-2002** [codemistic/Non-Code#32]
I would like to add web development resources for the beginners.

**Comment by AsmaKacem1** [comment]
Please assign me this task!

**Comment by Ayushbajpai19** [comment]
I want to contribute to this repo

**Comment by HIMU-2001** [comment]
Could I contribute to this part?

**Comment by AdityaBansal2310** [comment]
I can work on it . Please assign this to me.

**Comment by Satakshijain** [comment]
@gantavyamalviya I want to contribute to this . Please assign this to me

**Comment by TKirtan** [comment]
There are already lots of cheatsheets in repo.
You guys can go for some other beginner friendly issues and contributions.
