### ISSUE TITLE
Add binary trees sheet

### ISSUE THREAD

**Issue by jalanprakhar** [codemistic/Non-Code#36]
I have made an extensive sheet for revising binary trees for placement prep in c++ please assign this issue to me

**Comment by pratikrk** [comment]
I have created Notes On trees topic in coloured visualize format for better understanding along with code snippet and covered Following Topics : 
1. Max depth of Binary tree
2. Max depth of N-ary tree
3. Preorder of binary tree
4. Preorder of N-ary tree
5. Postorder of binary tree
6. Postorder of N-ary tree
7. Inorder of Binary tree
8. Merge two binary trees
9. Sum of root to leaf paths
10. Uni-valued Binary tree
11. Leaf similar trees
12. Binary tree paths
13. Sum of Left leaves
14. Path sum
15. Left view of Binary tree
16. Right view of Binary tree
17. Same tree
18. Invert Binary tree
19. Symmetric tree
20. Cousins of Binary tree

Hoping to get assign this task to me : Thank you

**Comment by Ankita-278** [comment]
please assign this task to me?

**Comment by AdityaBansal2310** [comment]
I can work on this issue. Please assign this to me
