### ISSUE TITLE
A blog on BASH Scripting

### ISSUE THREAD

**Issue by HumblePlebeian** [codemistic/Non-Code#38]
Hi, 
I would love to get an opportunity to work on a blog pertaining to BASH Scripting, describing everything that a reader must know to get comfortable with the technology, along with guided, hands on exercises that they can work on to test their knowledge.
Could you please assign this issue to me?
Thanks!

**Comment by AdityaBansal2310** [comment]
I would like to add my blog on BASH Scripting. Please assign this to me
