### ISSUE TITLE
Add linux cheat sheet

### ISSUE THREAD

**Issue by liferacer333** [codemistic/Non-Code#47]
I have 2 years of experience with linux. I would love to contribute to this.
Could you please assign this issue to me with hacktoberfest label

**Comment by Ayushbajpai19** [comment]
I would like to contribute to this repo for the hacktoberfest event.

**Comment by AdityaBansal2310** [comment]
I would like to contribute to this repo for HacktoberFest 2022

**Comment by jainshubham766** [comment]
i am good in linux. would like to resolve this issue.
