### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by BTANISHA11** [codemistic/Non-Code#63]
I want to add some sections in readme.md

1. how to make a pull request
2. how to create an issue
3. how to create a new branch
4. can you pls assign this to me @codemistic

**Comment by Abhash-Chakraborty** [comment]
Can you please assign me

**Comment by AdityaBansal2310** [comment]
Please assign this to me. I want to contribute to HacktoberFest 2022

**Comment by Atharva-Morankar-09** [comment]
Hey, I am new to open source and was looking to contribute to readme.md section.
In this section I was thinking of adding step by step procedure to create first pull request. If possible please assign this to me.
Thanks.

**Comment by TKirtan** [comment]
Please don't make repeated requests, You can contribute through making documentation on different topics, there are many ways to contribute even as beginner.
Read me file is already clear enough, doesn't need much chances.
